name: shrek pls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
# copy pasta its the same on either arch
# change reference for "Program Files" in x86, is there a better way to do this???
  build-64bit:
    runs-on: windows-latest
    steps:
    
      - name: Install v141_xp
        run: |
          mkdir D:\_temp
          cd D:\_temp
          Invoke-WebRequest -URI https://7-zip.org/a/7z2301-x64.exe -OutFile 7zip.exe
          ./7zip.exe /S
          git clone https://github.com/UMSKT/vslayout.git
          Get-Item -Path D:\_temp\vslayout\*.* | Move-Item -Destination D:\_temp
          Remove-Item D:\_temp\vslayout -Force -Recurse
          dir D:\_temp
          7z x D:\_temp\vslayout.7z.* -oD:\_temp\vslayout
          dir D:\_temp
          cmd.exe /c D:\_temp\vslayout\vs_BuildTools.exe --quiet --norestart --nocache --noweb --wait
          $Env:PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;" + $Env:PATH
          
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: asdsadsdsd
        run: |
          echo $Env:PATH
          where.exe cmake
          where.exe msbuild

      - name: Configure UMSKT
        uses: threeal/cmake-action@v1.2.0
        with:
          generator: "Visual Studio 17 2022"
          args: -A "x64" -T v141_xp

      - name: Build UMSKT
        working-directory: build
        run: msbuild ALL_BUILD.vcxproj /P:Configuration=Release /P:XPDeprecationWarning=false

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-Win64
          path: build/Release
