name: shrek pls

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
# copy pasta its the same on either arch
  build-64bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Configure UMSKT
        uses: threeal/cmake-action@v1.2.0
        with:
          generator: "Visual Studio 17 2022"
          args: -A "x64"

      - name: Build UMSKT
        working-directory: build
        run: msbuild ALL_BUILD.vcxproj /P:Configuration=Release /P:XPDeprecationWarning=false

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-Win64
          path: build/Release
